import connectDB from "../../utils/db";
import EmailLog from "../../models/EmailLog";

export default defineEventHandler(async (event) => {
  try {
    await connectDB();
    const body = await readBody(event);
    const { to, subject, notes, companyName, period, healthScore, completionPct } = body;

    if (!to) {
      return { success: false, error: 'Recipient email is required.' };
    }

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e5e7eb; border-radius: 12px;">
        <h2 style="color: #111827; margin-top: 0;">Sprint Health Executive Report — ${companyName || 'Project'}</h2>
        <p style="color: #6b7280; font-size: 14px;">Period: ${period || 'daily'}</p>
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;" />
        <div style="display: flex; gap: 20px; margin-bottom: 20px;">
          <div style="flex: 1; background: #ecfdf5; border-radius: 8px; padding: 15px; text-align: center;">
            <span style="display: block; font-size: 12px; color: #059669; font-weight: bold;">HEALTH SCORE</span>
            <span style="font-size: 28px; font-weight: bold; color: #059669;">${healthScore || 0}%</span>
          </div>
          <div style="flex: 1; background: #eff6ff; border-radius: 8px; padding: 15px; text-align: center;">
            <span style="display: block; font-size: 12px; color: #2563eb; font-weight: bold;">COMPLETION RATE</span>
            <span style="font-size: 28px; font-weight: bold; color: #2563eb;">${completionPct || 0}%</span>
          </div>
        </div>
        ${notes ? `<div style="background: #f9fafb; border-left: 4px solid #3b82f6; padding: 12px; margin-bottom: 20px; font-size: 14px; color: #374151;"><strong>Notes:</strong> ${notes}</div>` : ''}
        <p style="font-size: 13px; color: #9ca3af; text-align: center;">Generated by Sprintlytics Executive Dashboard</p>
      </div>
    `;

    const logEntry = await EmailLog.create({
      executionId: 'web-sprint-health-' + Date.now(),
      workflowId: 'sprint-health-dashboard',
      emailType: 'executive',
      status: 'SENT',
      delivered: true,
      to,
      recipientCount: 1,
      fromEmail: 'reports@sprintlytics.ai',
      subject: subject || `Sprint Health Report — ${companyName}`,
      htmlBody: htmlContent,
      htmlLength: htmlContent.length,
      sentAt: new Date(),
    });

    return {
      success: true,
      message: `Report successfully emailed to ${to}`,
      logId: logEntry._id,
    };
  } catch (error) {
    console.error('[API /api/sprint/email] Error:', error);
    return { success: false, error: error.message };
  }
});
